### ISSUE TITLE
Weird behavior - not masking and don't allow to save

### ISSUE THREAD

**Issue by jrvidotti** [dimitrov-adrian/directus-extension-masked-interface#4]
I could not get this extension to work. It doesn't mask fields and don't allow to save record, like screen recording below:

https://user-images.githubusercontent.com/5623041/160197309-5c4fd9df-074a-432a-b92c-58067cc5189d.mov

**Comment by bamboowonder** [comment]
I have the same issue.   And same behavior.  The masking doesn't appear, and clicking outside the textbox clears the value even if valid.  On save, it doesn't retain value.

**Comment by cristianocardoso0** [comment]
I also have the same issue, does not apply the mask and does not save the value.

I'm using directus 9.8.0

**Comment by cristianocardoso0** [comment]
@jrvidotti Conseguiu solucionar o problema?

**Comment by mateusmanm** [comment]
Estou com o mesmo problema. No console assim que a pagina é carregada, mostra esse erro.

![image](https://user-images.githubusercontent.com/56740952/164782913-aeebf57e-b867-48cd-82d4-9d0693f36003.png)

**Comment by dimitrov-adrian** [comment]
The issue comes after Directus 9.6. It is latest version 1.1.0

Sorry for the delay.
